// GENERATED by scripts/images.mjs — do not edit by hand.
export type Shot = { name: string; width: number; height: number; alt: string; lqip: string };
export const SHOTS = {
  "overview": {
    "name": "overview",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI Studio overview showing a live product, founder attention queue, product theatre and autonomous status",
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAgCdASoYAA0ALrV2u12jqampiYC0SygFh2K4TgrfkAD+8nqxsfDotzaxMj9q1GprV6T6YMUAAA=="
  },
  "approvals": {
    "name": "approvals",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI signed product plan showing the approved PRD, human signature and product screens",
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoYAA0APu1iqU2ppaOiMAgBMB2JZwC+SBuc0cRlH9k0z0AA/u6eWIhdk2nMzzgYTAc3K+lx2YWZdBl1ul5BUcmso5gzvWgA"
  },
  "governance": {
    "name": "governance",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI tamper-evident record showing human and autonomous decisions linked in a verified hash chain",
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAgCdASoYAA0ALrV2u12kqampiYC0SzgFp0K4STBqAAD+8jdIIjAs6bThxUQYeauSoQ/6wAA="
  },
  "members": {
    "name": "members",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI team and spend dashboard showing a live watch squad, its agent and current compute spend",
    "lqip": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoYAA0ABIBaJZwAA7wUQTlIAP7y+uF8XQjEdqN1N7Aw6cV2sgAAAA=="
  },
  "teamsync": {
    "name": "teamsync",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI build dashboard showing eight completed product scenes and the evidence attached to each shipped scene",
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYAA0ALrV2u12pKampiYC0SygFh2K4SFUAwAD+8fUZ1mE2LCPU8K3YBBNBgAAA"
  },
  "gatechain": {
    "name": "gatechain",
    "width": 2940,
    "height": 1598,
    "alt": "tOOrunt AI build verification chain showing eight completed scenes, proof checks and merged live work",
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYAA0ALrV2u12pKampiYC0SygFh2K4SFUAwAD+8fUZ1mE2LCPU8K3YBBNBgAAA"
  }
} as const satisfies Record<string, Shot>;
export type ShotName = keyof typeof SHOTS;
