/**
 * The four core surfaces, for the sticky-stack section.
 *
 * These are the product's real screens (public/shots, generated by
 * scripts/images.mjs) rather than illustration — the site's whole argument is
 * "built to be inspected", so the feature section shows the actual thing.
 *
 * Copy is verbatim from the live site, sourced per card below. Nothing here is
 * newly written marketing: if a claim is not on toorunt.ai today, it is not in
 * this file.
 *
 * Deliberately NOT the five-phase pipeline — that is the timeline's job
 * (content/timeline.ts). Running both would say the same thing twice.
 */

import type { ShotName } from "@/lib/shots";

export type Feature = {
  key: string;
  /** Rail number, rendered "01"…"04". */
  index: string;
  title: string;
  /** One-line thesis, sits directly under the title. */
  lead: string;
  /** The body. Verbatim from the page named in `source`. */
  body: string;
  shot: ShotName;
  source: string;
};

export const FEATURES: readonly Feature[] = [
  {
    key: "identities",
    index: "01",
    title: "One bot per teammate",
    lead: "Every action has an owner.",
    body:
      "Per-bot Jira and GitHub identities, with least-privilege tokens scoping each bot to its repos. A peer bot with its own GitHub identity reviews the change — a real, adversarial pass — so review is bot-to-bot, and it gates the merge.",
    shot: "members",
    source: "home · Act III comparison; security · control 03",
  },
  {
    key: "approvals",
    index: "02",
    title: "Every decision in one place",
    lead: "It never writes code before you approve the plan.",
    body:
      "The bot posts an implementation plan to Jira — files, approach, risks, acceptance criteria — and stops at the first human gate. Plans, PRs, infra and keys all queue in one inbox, so the three decisions that are actually yours are never buried in a feed.",
    shot: "approvals",
    source: "home · Human decision 01; shots.approvals alt",
  },
  {
    key: "governance",
    index: "03",
    title: "Every action, hash-chained",
    lead: "The log is either intact or provably altered.",
    body:
      "Each record commits to the one before it. Change any past decision and every subsequent hash breaks. Incident forensics and SOC 2 evidence are the same artifact — optionally HMAC-signed, and exportable.",
    shot: "governance",
    source: "security · tamper-evident audit",
  },
  {
    key: "fleet",
    index: "04",
    title: "A team that routes itself",
    lead: "Who to contact is deterministic.",
    body:
      "Bots claim tickets atomically, hold file-claim locks so two never touch the same surface, park when blocked, and hand off on failover. Escalation follows CODEOWNERS, git blame, Jira roles and on-call — a bounded ladder that always terminates.",
    shot: "teamsync",
    source: "product · the fleet",
  },
] as const;

if (process.env.NODE_ENV !== "production") {
  const keys = new Set(FEATURES.map((f) => f.key));
  if (keys.size !== FEATURES.length) throw new Error("FEATURES keys must be unique");
  FEATURES.forEach((f, i) => {
    const expected = String(i + 1).padStart(2, "0");
    if (f.index !== expected) {
      throw new Error(`FEATURES[${i}] index is "${f.index}", expected "${expected}"`);
    }
  });
}
