/**
 * tOOrunt AI site image pipeline — privacy-critical.
 *
 * Reads the Retina product screenshots from the external deck-screenshots
 * folder (filenames contain a U+202F narrow-no-break-space, so we glob and
 * match on the time token), crops off ALL Chrome and Claude Artifact UI, and
 * emits web assets into public/shots/. Originals never enter the repo.
 *
 * Also generates: src/lib/shots.ts (typed manifest w/ LQIP), OG images, icons.
 *
 * Run:  node scripts/images.mjs
 * Then: EYEBALL every public/shots/*-1100.webp at 100% for residual chrome.
 */
import sharp from "sharp";
import { readdirSync, mkdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SCREENSHOTS = process.env.TOORUNT_SCREENSHOTS
  ?? join(process.env.HOME, "Desktop", "toorunt-deck-screenshots");
const SHOTS_OUT = join(ROOT, "public", "shots");
const OG_OUT = join(ROOT, "public", "og");
mkdirSync(SHOTS_OUT, { recursive: true });
mkdirSync(OG_OUT, { recursive: true });

const captures = readdirSync(SCREENSHOTS).filter((f) => /^Screenshot 2026-07-29/.test(f));
const findByTime = (tok) => {
  const hit = captures.find((f) => f.includes(tok));
  if (!hit) throw new Error(`no screenshot matching time token ${tok}`);
  return join(SCREENSHOTS, hit);
};

// All July 29 captures are 2940×1912 Retina PNGs. The actual product begins at
// y=314; everything above it is either Chrome or Claude Artifact chrome. Keep
// the full product canvas — including its own sidebar and navigation — because
// those are part of the interface being demonstrated.
const PRODUCT_CROP = { left: 0, top: 314, width: 2940, height: 1598 };

const MANIFEST = [
  { name: "overview", tok: "10.07.46", crop: PRODUCT_CROP,
    alt: "tOOrunt AI Studio overview showing a live product, founder attention queue, product theatre and autonomous status" },
  { name: "approvals", tok: "10.08.10", crop: PRODUCT_CROP,
    alt: "tOOrunt AI signed product plan showing the approved PRD, human signature and product screens" },
  { name: "governance", tok: "10.09.00", crop: PRODUCT_CROP,
    alt: "tOOrunt AI tamper-evident record showing human and autonomous decisions linked in a verified hash chain" },
  { name: "members", tok: "10.09.08", crop: PRODUCT_CROP,
    alt: "tOOrunt AI team and spend dashboard showing a live watch squad, its agent and current compute spend" },
  { name: "teamsync", tok: "10.08.33", crop: PRODUCT_CROP,
    alt: "tOOrunt AI build dashboard showing eight completed product scenes and the evidence attached to each shipped scene" },
  { name: "gatechain", tok: "10.08.33", crop: PRODUCT_CROP,
    alt: "tOOrunt AI build verification chain showing eight completed scenes, proof checks and merged live work" },
];

const WIDTHS = [2200, 1100];

async function lqip(input, crop) {
  const buf = await sharp(input).extract(crop).resize(24).blur(1.2).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

const entries = [];
for (const m of MANIFEST) {
  const src = findByTime(m.tok);
  const base = sharp(src).extract(m.crop);
  const meta = { w: m.crop.width, h: m.crop.height };
  for (const w of WIDTHS) {
    const pipe = (fmt) => base.clone().resize(w).toFormat(fmt, fmt === "avif" ? { quality: 55 } : { quality: 78 });
    await pipe("avif").toFile(join(SHOTS_OUT, `${m.name}-${w}.avif`));
    await pipe("webp").toFile(join(SHOTS_OUT, `${m.name}-${w}.webp`));
  }
  const blur = await lqip(src, m.crop);
  entries.push({ name: m.name, width: meta.w, height: meta.h, alt: m.alt, lqip: blur });
  console.log(`✓ ${m.name}  ${meta.w}×${meta.h}  (from ${m.tok})`);
}

// Emit the typed manifest consumed by <BrowserFrame>.
const ts = `// GENERATED by scripts/images.mjs — do not edit by hand.
export type Shot = { name: string; width: number; height: number; alt: string; lqip: string };
export const SHOTS = ${JSON.stringify(
  Object.fromEntries(entries.map((e) => [e.name, e])),
  null,
  2
)} as const satisfies Record<string, Shot>;
export type ShotName = keyof typeof SHOTS;
`;
mkdirSync(join(ROOT, "src", "lib"), { recursive: true });
writeFileSync(join(ROOT, "src", "lib", "shots.ts"), ts);
console.log("✓ src/lib/shots.ts");

// ── OG images + icons (static; no runtime ImageResponse) ──────────────────────
const GROUND = "#f1efe9";
const INK = "#1a1b1e";
const ACCENT = "#8a7856";

function ogSvg(title, sub) {
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
  <rect width="1200" height="630" fill="${GROUND}"/>
  <radialGradient id="g" cx="80%" cy="0%" r="80%">
    <stop offset="0%" stop-color="${ACCENT}" stop-opacity="0.16"/>
    <stop offset="60%" stop-color="${ACCENT}" stop-opacity="0"/>
  </radialGradient>
  <rect width="1200" height="630" fill="url(#g)"/>
  <g transform="translate(80,120)">
    <circle cx="6" cy="0" r="5" fill="${INK}"/>
    <line x1="16" y1="0" x2="44" y2="0" stroke="#c6bfae" stroke-width="2"/>
    <circle cx="60" cy="0" r="13" fill="none" stroke="${ACCENT}" stroke-width="3"/>
    <circle cx="60" cy="0" r="5" fill="${ACCENT}"/>
    <line x1="76" y1="0" x2="104" y2="0" stroke="#c6bfae" stroke-width="2"/>
    <circle cx="114" cy="0" r="5" fill="${INK}"/>
    <text x="150" y="7" font-family="Georgia, serif" font-size="34" fill="${INK}">tOOrunt AI</text>
  </g>
  <text x="80" y="330" font-family="Georgia, serif" font-size="66" font-weight="500" fill="${INK}">${title}</text>
  <text x="82" y="410" font-family="Helvetica, Arial, sans-serif" font-size="28" fill="#9aa0a6">${sub}</text>
  <line x1="80" y1="520" x2="1120" y2="520" stroke="#ddd8cb" stroke-width="1"/>
  <text x="80" y="565" font-family="Helvetica, Arial, sans-serif" font-size="22" fill="#8f8a7d">Governed AI engineering teams · toorunt.ai</text>
</svg>`);
}

const OG = [
  ["home", "Engineers that aren’t people.", "One bot per teammate · 14 gates · a tamper-evident audit trail"],
  ["product", "From ticket to merged PR.", "Every step gated. Every action on the record."],
  ["security", "Worst case is a rejected pull request.", "14 gates · hash-chained audit · credential vault · kill switch"],
  ["pricing", "Priced per merged PR.", "$10–50 compute. $150 list. Margin on the dashboard."],
  ["manifesto", "The bottleneck is accountability.", "Not code generation — governance."],
];
for (const [name, title, sub] of OG) {
  await sharp(ogSvg(title, sub)).png().toFile(join(OG_OUT, `${name}.png`));
  console.log(`✓ og/${name}.png`);
}

// Favicon / apple-icon from the gate-node glyph.
const iconSvg = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180">
  <rect width="180" height="180" rx="40" fill="${GROUND}"/>
  <circle cx="90" cy="90" r="34" fill="none" stroke="${ACCENT}" stroke-width="9"/>
  <circle cx="90" cy="90" r="13" fill="${ACCENT}"/>
</svg>`);
await sharp(iconSvg).png().toFile(join(ROOT, "public", "apple-icon.png"));
console.log("✓ public/apple-icon.png");

console.log("\nDONE. Now eyeball public/shots/*-1100.webp for any residual chrome/bookmarks.");
